Introduction to Numpy


In [1]:
import numpy as np

To create an np array

In [2]:
arr = np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

TO create a multi-dimensional np array

In [7]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

it will show the shape of the array

In [38]:
arr2.shape

(2, 4)

It will show the size of the array

In [121]:
arr2.size

8

to access the the array with the index numbers like python list

In [39]:
arr2[0]

array([1, 2, 3, 4])

In [40]:
arr2[0][1]

2

Also like the original list, Python slice notation can be used for indexing.

In [41]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
arr2[0][:2]

array([1, 2])

list slices still refer to the original array, if the view can be mutated then the original array also changed

In [43]:
nums = np.array([1,2,3,4,5,6,7,8,9,0])

In [44]:
nums2 = nums[:5]
nums2

array([1, 2, 3, 4, 5])

In [45]:
nums2[0]=198
nums2

array([198,   2,   3,   4,   5])

In [46]:
nums

array([198,   2,   3,   4,   5,   6,   7,   8,   9,   0])

In [47]:
arr.ndim

1

to find the data type

In [50]:
arr.dtype

dtype('int64')

In [51]:
arr[0].dtype

dtype('int64')

to create a basic array

In [57]:
np.zeros(2,dtype='int64')

array([0, 0])

In [58]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [59]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [60]:
np.ones(10,dtype='int64')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [69]:
np.empty(12) 

array([5.03880719e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       1.20953760e-312, 4.79600257e-037, 2.90202494e+180, 9.32714636e+164,
       2.80416814e-032, 1.96785886e+160, 4.98242801e-037, 2.03994329e+160])

To create the range of numbers in the array. 

In [71]:
np.arange(4)

array([0, 1, 2, 3])

with specific range, step, starting

In [73]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

to create series of numbers from the specific range

In [89]:
np.linspace(0, 10, num=29)

array([ 0.        ,  0.35714286,  0.71428571,  1.07142857,  1.42857143,
        1.78571429,  2.14285714,  2.5       ,  2.85714286,  3.21428571,
        3.57142857,  3.92857143,  4.28571429,  4.64285714,  5.        ,
        5.35714286,  5.71428571,  6.07142857,  6.42857143,  6.78571429,
        7.14285714,  7.5       ,  7.85714286,  8.21428571,  8.57142857,
        8.92857143,  9.28571429,  9.64285714, 10.        ])

You can quickly sort the numbers in ascending order with:

In [106]:
arr = np.array([[2, 1, 5, 3,],[ 7, 4, 6, 8]])

In [107]:
np.sort(arr)

array([[1, 2, 3, 5],
       [4, 6, 7, 8]])

we can mention which that wich sorting algorithm we nedd to use kind{‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’},

In [112]:
np.argsort(arr,kind='heapsort')

array([[1, 0, 3, 2],
       [1, 2, 0, 3]])

it will give the index of the number incase it is present in an sorted array

In [120]:
np.searchsorted([11,12,13,14,15], 11.5)

1

You can use reshape() to reshape your array.

In [183]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [184]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [185]:
np.reshape(arr, newshape=(2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [186]:
arr.shape

(6,)

to covert a 1D to 2D array for row vextor(row vise)

In [189]:
arr2 = arr[np.newaxis,:]
arr2

array([[0, 1, 2, 3, 4, 5]])

In [190]:
arr2.shape

(1, 6)

to covert again into 3D from 2D , agian call the same function

In [191]:
arr3 = arr2[np.newaxis,:]
arr3

array([[[0, 1, 2, 3, 4, 5]]])

In [192]:
arr3.shape

(1, 1, 6)

to covert a 1D to 2D array for row vextor(column vise)

In [193]:
arr = np.arange(6)

In [195]:
arr2 = arr[:,np.newaxis]
arr2

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [198]:
arr2.shape

(6, 1)

In [196]:
arr3 = arr2[:,np.newaxis]
arr3

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [197]:
arr3.shape

(6, 1, 1)

Using expandims to convert the 1D to 2D

In [199]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

expand by column vise

In [200]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

expand by row vise

In [201]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [2]:
import numpy as np
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

we can extract the elements in the array by also applying some conditions

In [7]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [8]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [10]:
c = a[(a > 2) & (a < 5)]
c

array([3, 4])

vstack append in vertically (colomn vise)

In [15]:
arr = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr2 = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
k =np.vstack((arr,arr2))
k

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

vstack append in horizontally (row vise)

In [17]:
np.hstack((arr,arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

If you wanted to split this array into three equally shaped arrays, you would run

In [19]:
np.hsplit(arr, 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

 If you want to find the sum of the elements in an array, you’d use sum()

In [20]:
a = np.array([1,2,3])

In [21]:
a.sum()

6

To sum in the row vise

In [27]:
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [24]:
a.sum(axis=0)

array([5, 7, 9])

To sum in the column vise

In [25]:
a.sum(axis=1)

array([ 6, 15])

In [28]:
a.max()

6

In [29]:
a.min()

1

to get unique number and its index

In [32]:
unique_values,index  = np.unique(arr, return_index=True)

In [35]:
unique_values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
index

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
k

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [39]:
k.transpose()

array([[ 1,  1],
       [ 2,  2],
       [ 3,  3],
       [ 4,  4],
       [ 5,  5],
       [ 6,  6],
       [ 7,  7],
       [ 8,  8],
       [ 9,  9],
       [10, 10]])

In [42]:
np.flip(k)

array([[10,  9,  8,  7,  6,  5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6,  5,  4,  3,  2,  1]])

to combine multi dimensional arrays into single dimensional array 

In [44]:
k.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

It is also used to combine multi dimensional arrays into single dimensional array however it does not create a new copy of array it jut refer to the original array , so if any changes made it will affect to the main array.

In [52]:
k.ravel()

array([ 1,  2,  3,  4,  5,  6,  7, 99,  9, 10,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

To access the dockstring of any function in numpy you can access it by help method

In [54]:
help(min)

Help on built-in function min in module builtins:

min(...)
    min(iterable, *[, default=obj, key=func]) -> value
    min(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its smallest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the smallest argument.



In [57]:
help(np.hstack)

Help on function hstack in module numpy:

hstack(tup)
    Stack arrays in sequence horizontally (column wise).
    
    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays.
    
    See Also
    --------
    concatenate : Join a sequence of arrays along an existing axis.
    s

How to save and load NumPy objects

In [58]:
a = np.array([1, 2, 3, 4, 5, 6])

In [59]:
np.save('filename', a)

In [60]:
b = np.load('filename.npy')

In [61]:
b

array([1, 2, 3, 4, 5, 6])